apiVersion: apps/v1
kind: Deployment
metadata: 
  name: url-shortener

spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template: 
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: url-shortener:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-atlas-secret
              key: MONGO_URI